name: CI
on:
  push:
  workflow_dispatch:

jobs:
  testing-my-gh-action-yo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: installing dependencies 
        run: mvn clean package
      - name: building project
        run: mvn run build
      - name: running tests
        run: mvn test
